local configString = [[
_G.Settings = {
    Main = {
        ["Auto Farm Level"] = false,
        ["Fast Auto Farm Level"] = false,
        ["Distance Mob Aura"] = 1000,
        ["Mob Aura"] = false,
        ["Auto New World"] = false,
        ["Auto Saber"] = false,
        ["Auto Pole"] = false,
        ["Auto Buy Ablility"] = false,
        ["Auto Third Sea"] = false,
        ["Auto Factory"] = false,
        ["Auto Factory Hop"] = false,
        ["Auto Bartilo Quest"] = false,
        ["Auto True Triple Katana"] = false,
        ["Auto Rengoku"] = false,
        ["Auto Swan Glasses"] = false,
        ["Auto Dark Coat"] = false,
        ["Auto Ectoplasm"] = false,
        ["Auto Buy Legendary Sword"] = false,
        ["Auto Buy Enchanment Haki"] = false,
        ["Auto Holy Torch"] = false,
        ["Auto Buddy Swords"] = false,
        ["Auto Farm Boss Hallow"] = false,
        ["Auto Rainbow Haki"] = false,
        ["Auto Elite Hunter"] = false,
        ["Auto Musketeer Hat"] = false,
        ["Auto Buddy Sword"] = false,
        ["Auto Farm Bone"] = false,
        ["Auto Ken-Haki V2"] = false,
        ["Auto Cavander"] = false,
        ["Auto Yama Sword"] = false,
        ["Auto Tushita Sword"] = false,
        ["Auto Serpent Bow"] = false,
        ["Auto Dark Dagger"] = false,
        ["Auto Cake Prince"] = false,
        ["Auto Dough V2"] = false,
        ["Auto Random Bone"] = false,
        ["Auto Fish Tail Sea 1"] = false,
        ["Auto Fish Tail Sea 3"] = false,
        ["Auto Magma Ore Sea 2"] = false,
        ["Auto Magma Ore Sea 1"] = false,
        ["Auto Mystic Droplet"] = false,
        ["Auto Dragon Scales"] = false,
    },
    FightingStyle = {
        ["Auto God Human"] = false,
        ["Auto Superhuman"] = false,
        ["Auto Electric Claw"] = false,
        ["Auto Death Step"] = false,
        ["Auto Fully Death Step"] = false,
        ["Auto SharkMan Karate"] = false,
        ["Auto Fully SharkMan Karate"] = false,
        ["Auto Dragon Talon"] = false,
    },
    Boss = {
        ["Auto All Boss"] = false,
        ["Auto Boss Select"] = false,
        ["Select Boss"] = {},
        ["Auto Quest"] = false,
    },
    Mastery = {
        ["Select Multi Sword"] = {},
        ["Farm Mastery SwordList"] = false,
        ["Auto Farm Fruit Mastery"] = false,
        ["Auto Farm Gun Mastery"] = false,
        ["Mob Health (%)"] = 15,
    },
    Configs = {
        ["Double Quest"] = false,
        ["Bypass TP"] = false,
        ["Select Team"] = {"Pirate"},
        ["Fast Attack"] = true,
        ["Fast Attack Type"] = {"Fast"},
        ["Select Weapon"] = {},
        ["Auto Haki"] = true,
        ["Distance Auto Farm"] = 20,
        ["Camera Shaker"] = false,
        ["Skill Z"] = true,
        ["Skill X"] = true,
        ["Skill C"] = true,
        ["Skill V"] = true,
        ["Show Hitbox"] = false,
        ["Bring Mob"] = true,
        ["Disabled Damage"] = false,
    },
    Stat = {
        ["Enabled Auto Stats"] = false,
        ["Auto Stats Kaitun"] = false,
        ["Select Stats"] = {"Melee"},
        ["Point Select"] = 3,
        ["Enabled Auto Redeem Code"] = false,
        ["Select Level Redeem Code"] = 1,
    },
    Misc = {
        ["No Soru Cooldown"] = false,
        ["No Dash Cooldown"] = false,
        ["Infinities Geppo"] = false,
        ["Infinities Energy"] = false,
        ["No Fog"] = false,
        ["Wall-TP"] = false,
        ["Fly"] = false,
        ["Fly Speed"] = 1,
        ["Auto Rejoin"] = true,
    },
    Teleport = {
        ["Teleport to Sea Beast"] = false,
    },
    Fruits = {
        ["Auto Buy Random Fruits"] = false,
        ["Auto Store Fruits"] = false,
        ["Select Devil Fruits"] = {},
        ["Auto Buy Devil Fruits Sniper"] = false,
    },
    Raids = {
        ["Auto Raids"] = false,
        ["Kill Aura"] = false,
        ["Auto Awakened"] = false,
        ["Auto Next Place"] = false,
        ["Select Raids"] = {},
    },
    Combat = {
        ["Fov Size"] = 200,
        ["Show Fov"] = false,
        ["Aimbot Skill"] = false,
    },
    HUD = {
        ["FPS"] = 60,
        ["LockFPS"] = true,
        ["Boost FPS Windows"] = false,
        ['White Screen'] = false,
    },
    ConfigsUI = {
        ColorUI = Color3.fromRGB(255, 0, 127),
    }
}
]]
